from pathlib import Path
from typing import IO

import click
from loguru import logger

from metabintools.bin_utils import find_binsfiles
from metabintools.dataclasses.binset import BinSet
from metabintools.export.binset_exporter import BinSetExporter


@click.command("binset")
@click.option(
    "--compress",
    "-z",
    "compress",
    is_flag=True,
    help="(optional) Compress the output using zstd.",
)
@click.option(
    "--group",
    type=str,
    help="Name to assign to the group of bins",
    required=True,
)
@click.option(
    "--binsplit-separator",
    type=str,
    help="Separator character to recover original contig names if bins were generated by SemiBin2, VAMB, or another binsplitting binner (optional)",
    required=False,
)
@click.option("--output", "-o", type=click.File("wb"), default="-", required=False)
@click.argument(
    "binsfile",
    type=click.File("rb"),
    required=True,
    default="-",
    help="The BINS file to add bins to.",
)
@click.argument(
    "fasta",
    type=click.Path(exists=True, dir_okay=True, file_okay=True),
    nargs=-1,
    required=True,
    help="Bin FASTA files, or directories containing bin FASTA files",
)
def import_binset(
    binsfile: IO,
    fasta: list[str],
    group: str,
    output: IO,
    compress: bool = False,
    binsplit_separator: str | None = None,
):
    """Add a set of bins to a BINS file."""
    try:
        logger.info("Reading BINS file...")
        binset = BinSet.read_binsfile(binsfile)

        logger.info(f"Locating bin files from {len(fasta)} input(s)...")
        bin_directories_files = [
            find_binsfiles(Path(dir)) for dir in fasta if Path(dir).is_dir()
        ]
        bins_direct_files = [Path(file) for file in fasta if Path(file).is_file()]
        bin_files = [
            item for sublist in bin_directories_files for item in sublist
        ] + bins_direct_files

        if not bin_files:
            logger.error("No bin FASTA files found in the provided paths")
            raise click.ClickException("No bin FASTA files found in the provided paths")

        logger.info(f"Found {len(bin_files)} bin file(s) to import")

        logger.info(f"Adding {len(bin_files)} bin(s) to binset with group '{group}'...")
        try:
            out_binset = binset.add_bins_from_fasta(
                bin_files,
                group=group,
                binsplit_separator=binsplit_separator,
            )
        except RuntimeError as e:
            logger.error(f"Failed to add bins: {e}")
            raise click.ClickException(f"Failed to add bins: {e}")

        logger.info("Writing BINS file...")
        BinSetExporter(out_binset).write_binsfile(output, compress=compress)
        logger.info("Binset import completed successfully.")

    except click.ClickException:
        raise
    except OSError as e:
        logger.error(f"File I/O error: {e}")
        raise click.ClickException(f"File I/O error: {e}")
